name: mustache4dart
version: 0.0.8+0.4.1.0
author: Georgios Valotasios <valotas@gmail.com>
description: A mustache implementation for the Dart language
homepage: https://github.com/valotas/mustache4dart
dependencies:
  unittest: any

#  js: any